// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JqKXnB3tJ9GHK0h2c7fkOoCJtbMU_SA',
    appId: '1:1095716158893:web:ae9ff59e4c112bf4e63524',
    messagingSenderId: '1095716158893',
    projectId: 'huit-demo',
    authDomain: 'huit-demo.firebaseapp.com',
    storageBucket: 'huit-demo.firebasestorage.app',
    measurementId: 'G-2ET03L6435',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5s7m-YON7KFP9-KbdiaoC7ywZFW0-eE',
    appId: '1:1095716158893:android:5510a03d84c4faa5e63524',
    messagingSenderId: '1095716158893',
    projectId: 'huit-demo',
    storageBucket: 'huit-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfx6pBjns-YXaGOEGhd1wmvBQIv1XOrg',
    appId: '1:1095716158893:ios:e858c7bb27ec58bbe63524',
    messagingSenderId: '1095716158893',
    projectId: 'huit-demo',
    storageBucket: 'huit-demo.firebasestorage.app',
    iosBundleId: 'com.example.demoTopic10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlfx6pBjns-YXaGOEGhd1wmvBQIv1XOrg',
    appId: '1:1095716158893:ios:e858c7bb27ec58bbe63524',
    messagingSenderId: '1095716158893',
    projectId: 'huit-demo',
    storageBucket: 'huit-demo.firebasestorage.app',
    iosBundleId: 'com.example.demoTopic10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2JqKXnB3tJ9GHK0h2c7fkOoCJtbMU_SA',
    appId: '1:1095716158893:web:9bed882e8341f28fe63524',
    messagingSenderId: '1095716158893',
    projectId: 'huit-demo',
    authDomain: 'huit-demo.firebaseapp.com',
    storageBucket: 'huit-demo.firebasestorage.app',
    measurementId: 'G-DM7329BJDL',
  );
}
